### ISSUE TITLE
maven problem

### ISSUE THREAD

**Issue by p-frolov** [USPTO/PatentPublicData#65] opened 2017-12-10 18:26 UTC
Hi,
I am not sure exactly about cause of problem. I tried to build the project by `mvn package` or `mvn install`:

[WARNING] The following dependencies could not be resolved at this point of the build but seem to be part of the reactor:
[WARNING] o gov.uspto:Common:jar:0.0.1-SNAPSHOT (compile)
[WARNING] Try running the build up to the lifecycle phase "package"
[WARNING] The following dependencies could not be resolved at this point of the build but seem to be part of the reactor:
[WARNING] o gov.uspto:Common:jar:0.0.1-SNAPSHOT (compile)
[WARNING] o gov.uspto:PatentDocument:jar:0.0.1-SNAPSHOT (compile)
[WARNING] Try running the build up to the lifecycle phase "package"
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4.1:single (default) on project PatentPublicData: Assembly is incorrectly configured: null: Assembly is incorrectly configured: null:
[ERROR] Assembly: null is not configured correctly: Assembly ID must be present and non-empty.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

`mvn compile` returns SUCCESS by the way:
[INFO] PatentPublicData ................................... SUCCESS [  0.004 s]
[INFO] Common ............................................. SUCCESS [  1.086 s]
[INFO] PatentDocument ..................................... SUCCESS [  0.374 s]
[INFO] BulkDownloader ..................................... SUCCESS [  0.167 s]

can you help me with this issue, I don't java programmer, but I need to parse some patents.

**Comment by bgfeldm** [comment] 2019-02-07 14:21
Closing issue, I can't reproduce. Maybe the issue has already been fixed.

**Closed by bgfeldm** 2019-02-07 14:21 UTC
